// apache-arrow as an ES module: what `import { tableFromIPC } from
// 'apache-arrow'` resolves to. GENERATED by scripts/fetch-appassets.sh
// from arrow.min.js's own exports; do not edit by hand.
//
// arrow.min.js is the upstream UMD build, which cannot be imported: its
// wrapper assigns `this.Arrow`, and `this` is undefined in a module. So
// this loads it as a classic script -- once, and not at all when the
// page already has <script src="vendor/arrow.min.js"> -- and re-exports
// the global it defines.
if (!globalThis.Arrow) {
  await new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = new URL('./arrow.min.js', import.meta.url).href;
    script.onload = resolve;
    script.onerror = () =>
      reject(new Error('apache-arrow: vendor/arrow.min.js did not load'));
    document.head.appendChild(script);
  });
}
const Arrow = globalThis.Arrow;
export default Arrow;
export const {
  AsyncByteQueue, AsyncByteStream, AsyncMessageReader,
  AsyncRecordBatchFileReader, AsyncRecordBatchStreamReader, Binary,
  BinaryBuilder, BinaryView, BinaryViewBuilder, Bool, BoolBuilder,
  BufferType, Builder, ByteStream, CompressionType, Data, DataType,
  DateBuilder, DateDay, DateDayBuilder, DateMillisecond,
  DateMillisecondBuilder, DateUnit, Date_, Decimal, DecimalBuilder,
  DenseUnion, DenseUnionBuilder, Dictionary, DictionaryBuilder, Duration,
  DurationBuilder, DurationMicrosecond, DurationMicrosecondBuilder,
  DurationMillisecond, DurationMillisecondBuilder, DurationNanosecond,
  DurationNanosecondBuilder, DurationSecond, DurationSecondBuilder,
  Field, FixedSizeBinary, FixedSizeBinaryBuilder, FixedSizeList,
  FixedSizeListBuilder, Float, Float16, Float16Builder, Float32,
  Float32Builder, Float64, Float64Builder, FloatBuilder, Int, Int16,
  Int16Builder, Int32, Int32Builder, Int64, Int64Builder, Int8,
  Int8Builder, IntBuilder, Interval, IntervalBuilder, IntervalDayTime,
  IntervalDayTimeBuilder, IntervalMonthDayNano,
  IntervalMonthDayNanoBuilder, IntervalUnit, IntervalYearMonth,
  IntervalYearMonthBuilder, JSONMessageReader, LargeBinary,
  LargeBinaryBuilder, LargeList, LargeListBuilder, LargeUtf8,
  LargeUtf8Builder, List, ListBuilder, MapBuilder, MapRow, Map_, Message,
  MessageHeader, MessageReader, MetadataVersion, Null, NullBuilder,
  Precision, RecordBatch, RecordBatchFileReader, RecordBatchFileWriter,
  RecordBatchJSONWriter, RecordBatchReader, RecordBatchStreamReader,
  RecordBatchStreamWriter, RecordBatchWriter, Schema, SparseUnion,
  SparseUnionBuilder, Struct, StructBuilder, StructRow, Table, Time,
  TimeBuilder, TimeMicrosecond, TimeMicrosecondBuilder, TimeMillisecond,
  TimeMillisecondBuilder, TimeNanosecond, TimeNanosecondBuilder,
  TimeSecond, TimeSecondBuilder, TimeUnit, Timestamp, TimestampBuilder,
  TimestampMicrosecond, TimestampMicrosecondBuilder,
  TimestampMillisecond, TimestampMillisecondBuilder, TimestampNanosecond,
  TimestampNanosecondBuilder, TimestampSecond, TimestampSecondBuilder,
  Type, Uint16, Uint16Builder, Uint32, Uint32Builder, Uint64,
  Uint64Builder, Uint8, Uint8Builder, Union, UnionBuilder, UnionMode,
  Utf8, Utf8Builder, Utf8View, Utf8ViewBuilder, Vector, Visitor,
  builderThroughAsyncIterable, builderThroughIterable,
  compressionRegistry, isArrowData, isArrowDataType, isArrowField,
  isArrowRecordBatch, isArrowSchema, isArrowTable, isArrowVector,
  makeBuilder, makeData, makeTable, makeVector, tableFromArrays,
  tableFromIPC, tableFromJSON, tableToIPC, util, vectorFromArray,
} = Arrow;
